name: test

on:
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:

jobs:
  call-test:
    uses: ./.github/workflows/unit_test.yaml
  status-check:
    runs-on: ubuntu-latest
    needs: [call-test]
    if: always()
    steps:
      - run: |
          [[ ${{ needs.call-test.result }} == 'success' ]] && exit 0
          exit 1
